"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(2, 3);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(2, 3, 5);
console.log(myCircle.getInfo());
var reactangle = new Rectangle_1.Reactangle(0, 0, 2, 4);
console.log(reactangle.getInfo());
